version: "3"
services:
  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gurubase}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gurubot}
    volumes:
      - db-data:/var/lib/postgres/data:rw
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 5
      timeout: 5s
      interval: 10s

  gurubot:
    build: .
    command: node build/main.js
    environment:
      - GURUBOT_TOKEN=${GURUBOT_TOKEN}
      - DB_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-gurubot}@${POSTGRES_HOST:-db}:5432/${POSTGRES_DB:-gurubase}?schema=${POSTGRES_SCHEMA:-guru}
    depends_on:
      - db
    links:
      - db

volumes:
  db-data: