version: "3"
services:
  gurubot:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${GURUBOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE:-gurubase}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql/data:rw
    ports:
        - "3306:3306"

volumes:
  db-data: