version: "3"
services:
  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgres/data:rw
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 5
      timeout: 5s
      interval: 10s
  gurubot:
    build: .
    command: node build/main.js
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

volumes:
  db-data: