version: "3"
services:
  gurubot:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${GURUBOT_TOKEN}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_DB=${POSTGRES_DB:-gurubase}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA:-guru}
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gurubase}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgres/data:rw
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 5
      timeout: 5s
      interval: 10s

volumes:
  db-data: