version: "3"
services:
  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: "gurubot-db"
    restart: always
    volumes:
      - gurubot-db:/var/lib/postgres/data:rw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      retries: 5
      timeout: 5s
      interval: 10s
    env_file:
      - .env
  gurubot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "gurubot"
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  gurubot-db:

networks:
  default:
    name: gurubot-network
